### ISSUE TITLE
Unable to Load Server Side plugin

### ISSUE THREAD

**Issue by devu** [dodexahedron/EssentialsPlugin#12]
Using latest version of extender: SEServerExtender-v1.76.11.375-alpha

Here is what I get after initial load:
Error: System.TypeLoadExeption: Method 'get_Version' in type EssentialsPlugin.Essentials' from assembly 'Essentials, Version=1.4.0.2237, Culture=neutral, PublicKeyToken=null, does not have an implementation. 
at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeASsembly assembly, ObjectHandleOnStack, retTypes)
at System.Reflection.RuntimeAssembly.GetExportedTypes()
at SEModAPIExtensions.API.PluginManager.IsOldPlugin(Assembly assembly)
at SEModAPIExtensions.API.PluginManager.LoadPlugin(Boolean forceLoad)

Results in Essential Plugin not being loaded at all.

**Comment by dodexahedron** [comment]
I specified in the release notes that you have to update plugins (including essentials).
You're using a very old version of essentials, which is incompaible.
Please update and you'll be all set:
https://github.com/SEServerExtender/EssentialsPlugin/releases
